### ISSUE TITLE
Support GCR

### ISSUE THREAD

**Issue by watiko** [nearmap/cvmanager#31]
GCR(Google Container Registry) is not supported by both `Docker Registry Syncer` and `Docker Registry Tagger` according to the README.

Is there any chance it will be supported?

**Comment by simoncochrane** [comment]
Hi watiko,

Yes, we plan to support GCR in the future. Given that GCR, Quay and Dockerhub all support the Docker V2 Registry API it makes sense to tick them all off with a common implementation.

Currently we are doing a major refactor and finalizing the container registry interfaces, at which point we can look at this.

**Comment by suneeta-mall** [comment]
Closing this in favour of https://github.com/nearmap/cvmanager/issues/15
